#!/bin/bash

rsync -aP --exclude '.git' --exclude 'pullFromTalapas' --exclude 'push2Talapas' aashraf@login.talapas.uoregon.edu:/projects/proteus/aashraf/seismic-picker-ml/ /Users/asifashraf/documents/code_repo/seismic-picker-ml/