#!/bin/bash

rsync -aP --exclude 'features' --exclude 'predictions' --exclude 'push2Talapas' --exclude 'pullFromTalapas' --exclude '.git' /Users/asifashraf/documents/code_repo/seismic-picker-ml/ aashraf@login.talapas.uoregon.edu:/projects/proteus/aashraf/seismic-picker-ml/